networks:
  listtick-network:
    external: true

services:
  keycloak:
    image: pjatksuml/listtick-keycloak:latest
    command: ["start", "--https-port=8443"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://listtick-db:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: admin

      KC_PROXY: edge
      KC_HOSTNAME: ${PUBLIC_HOST}
      KC_HOSTNAME_STRICT: "true"
      KC_HOSTNAME_STRICT_HTTPS: "true"
      KC_HTTP_RELATIVE_PATH: /auth

      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/tls/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/tls/tls.key
    volumes:
      - /home/ec2-user/app/kc-certs:/opt/keycloak/tls:ro
    networks:
      listtick-network:
        aliases:
          - keycloak

  listtick:
    image: pjatksuml/listtick-backend:latest
    volumes:
      - /home/ec2-user/app/kc-certs/keycloak-ca.pem:/opt/certs/keycloak-ca.pem:ro
    environment:
      - JAVA_TOOL_OPTIONS=-Djavax.net.ssl.trustStore=/tmp/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
    entrypoint: [ "/bin/sh","-c",
      "keytool -importcert -noprompt -alias keycloak-ca -file /opt/certs/keycloak-ca.pem -keystore /tmp/truststore.jks -storepass changeit && \
       exec java -jar /app/app.jar --spring.profiles.active=prod"
    ]
    networks:
      listtick-network:
        aliases:
          - listtick

  frontend:
    image: pjatksuml/listtick-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ec2-user/app/nginx:/etc/nginx/conf.d:ro
      - /home/ec2-user/app/frontend-certs/tls.crt:/etc/nginx/certs/tls.crt:ro
      - /home/ec2-user/app/frontend-certs/tls.key:/etc/nginx/certs/tls.key:ro
    networks:
      - listtick-network
